(()=>{
const mode=document.getElementById('branchMode'),canvas=mode?.querySelector('.branchCanvas'),siblings=mode?.querySelector('.siblings');if(!mode||!canvas)return;const NS='http://www.w3.org/2000/svg';
const css=document.createElement('style');css.textContent=`.branchMode{background:radial-gradient(circle at 50% 48%,#fff 0,#f6f4ee 54%,#ecebe4 100%)!important}.branchMode .branchSvg{display:none!important}.branchLiveGraph{position:absolute;inset:0;width:100%;height:100%;z-index:1;overflow:visible;pointer-events:none}.branchLiveGraph path{fill:none;stroke-linecap:round;stroke-linejoin:round;vector-effect:non-scaling-stroke}.branchLiveGraph .rootLine{stroke:#111713;stroke-width:6}.branchLiveGraph .midLine{stroke:#007a3d;stroke-width:4}.branchLiveGraph .newLine{stroke:#ce1126;stroke-width:2.8}.branchLiveGraph circle{fill:#fff;stroke-width:2.5;vector-effect:non-scaling-stroke}.branchLiveGraph .rootDot{stroke:#111713}.branchLiveGraph .midDot{stroke:#007a3d}.branchLiveGraph .newDot{stroke:#ce1126}.branchMode .slot,.branchMode .addDynamic{z-index:3}.branchMode .siblings{left:0!important;right:0!important;height:1px!important;display:block!important;pointer-events:none}.branchMode .siblings .slot{position:absolute!important;top:0!important;transform:translate(-50%,-50%)!important;pointer-events:auto!important;transition:left .5s cubic-bezier(.16,.85,.2,1)!important}@media(max-width:700px){.branchMode .siblings .slot{width:115px!important}}`;document.head.appendChild(css);
let svg=canvas.querySelector('.branchLiveGraph');if(!svg){svg=document.createElementNS(NS,'svg');svg.setAttribute('class','branchLiveGraph');canvas.prepend(svg)}let prevKeys=new Set(),raf=0;
function rename(){mode.querySelectorAll('.siblings .slot small').forEach(x=>x.textContent='Hermano');mode.querySelectorAll('.children .slot small').forEach(x=>x.textContent='Hijo')}
function alignSiblings(){const me=mode.querySelector('.me .slotBtn'),slots=[...mode.querySelectorAll('.siblings .slot')];if(!me||!siblings)return;const cr=canvas.getBoundingClientRect(),mr=me.getBoundingClientRect();const meY=mr.top+mr.height/2-cr.top;siblings.style.top=meY+'px';const gap=Math.max(145,Math.min(180,canvas.clientWidth*.145));slots.forEach((s,i)=>{const step=Math.floor(i/2)+1,dir=i%2===0?-1:1;s.style.left=`calc(50% + ${dir*step*gap}px)`;s.style.top='0px'})}
function point(el){if(!el)return null;const cr=canvas.getBoundingClientRect(),r=el.getBoundingClientRect();return{x:r.left+r.width/2-cr.left,y:r.top+r.height/2-cr.top}}
function geometry(a,b){const horizontal=Math.abs(a.y-b.y)<5;if(horizontal){const dx=b.x-a.x;return`M ${a.x} ${a.y} C ${a.x+dx*.34} ${a.y}, ${b.x-dx*.34} ${b.y}, ${b.x} ${b.y}`}const bend=Math.max(28,Math.abs(b.y-a.y)*.38);return`M ${a.x} ${a.y} C ${a.x} ${a.y-bend}, ${b.x} ${b.y+bend}, ${b.x} ${b.y}`}
function makePath(a,b,cls,key,newKeys){if(!a||!b)return;let p=svg.querySelector(`path[data-key="${key}"]`);const fresh=!p;if(!p){p=document.createElementNS(NS,'path');p.dataset.key=key;p.setAttribute('class',cls);svg.appendChild(p)}p.setAttribute('d',geometry(a,b));newKeys.add(key);if(fresh&&prevKeys.size){let len=300;try{len=p.getTotalLength()}catch(_){}p.style.strokeDasharray=String(len);p.style.strokeDashoffset=String(len);requestAnimationFrame(()=>{p.style.transition='stroke-dashoffset .82s cubic-bezier(.16,.85,.2,1)';p.style.strokeDashoffset='0';setTimeout(()=>{p.style.transition='none';p.style.strokeDasharray='none';p.style.strokeDashoffset='0'},850)})}else{p.style.strokeDasharray='none';p.style.strokeDashoffset='0'}}
function syncDot(a,cls,key,newKeys){if(!a)return;let c=svg.querySelector(`circle[data-key="${key}"]`);if(!c){c=document.createElementNS(NS,'circle');c.dataset.key=key;c.setAttribute('r','4');c.setAttribute('class',cls);svg.appendChild(c)}c.setAttribute('cx',a.x);c.setAttribute('cy',a.y);newKeys.add(key)}
function render(){raf=0;rename();alignSiblings();requestAnimationFrame(()=>{const me=point(mode.querySelector('.me .slotBtn')),father=point(mode.querySelector('.father .slotBtn')),mother=point(mode.querySelector('.mother .slotBtn')),gf=point(mode.querySelector('.gf .slotBtn')),gm=point(mode.querySelector('.gm .slotBtn')),gf2=point(mode.querySelector('.gf2 .slotBtn')),gm2=point(mode.querySelector('.gm2 .slotBtn')),newKeys=new Set();makePath(gf,father,'rootLine','p-gf-f',newKeys);makePath(gm,father,'rootLine','p-gm-f',newKeys);makePath(gf2,mother,'rootLine','p-gf2-m',newKeys);makePath(gm2,mother,'rootLine','p-gm2-m',newKeys);makePath(father,me,'midLine','p-f-me',newKeys);makePath(mother,me,'midLine','p-m-me',newKeys);[...mode.querySelectorAll('.siblings .slot .slotBtn')].forEach((el,i)=>makePath(me,point(el),'midLine','p-sib-'+i,newKeys));[...mode.querySelectorAll('.children .slot .slotBtn')].forEach((el,i)=>makePath(me,point(el),'newLine','p-child-'+i,newKeys));[[gf,'rootDot','d-gf'],[gm,'rootDot','d-gm'],[gf2,'rootDot','d-gf2'],[gm2,'rootDot','d-gm2'],[father,'midDot','d-f'],[mother,'midDot','d-m'],[me,'midDot','d-me']].forEach(x=>syncDot(x[0],x[1],x[2],newKeys));[...mode.querySelectorAll('.siblings .slot .slotBtn')].forEach((el,i)=>syncDot(point(el),'midDot','d-sib-'+i,newKeys));[...mode.querySelectorAll('.children .slot .slotBtn')].forEach((el,i)=>syncDot(point(el),'newDot','d-child-'+i,newKeys));[...svg.querySelectorAll('[data-key]')].forEach(el=>{if(!newKeys.has(el.dataset.key))el.remove()});prevKeys=newKeys})}
function schedule(){if(raf)return;raf=requestAnimationFrame(render)}
new MutationObserver(ms=>{if(ms.some(m=>m.type==='childList'&&[...m.addedNodes,...m.removedNodes].some(n=>n.nodeType===1)))schedule()}).observe(canvas,{childList:true,subtree:true});window.addEventListener('resize',schedule);new MutationObserver(()=>{if(mode.classList.contains('open'))setTimeout(schedule,50)}).observe(mode,{attributes:true,attributeFilter:['class']});render();
})();