(()=>{
const viewport=document.getElementById('treeViewport'),familyView=document.getElementById('familyView'),fg=familyView?.querySelector('.kinGraph'),kinPeople=document.getElementById('kinPeople'),back=document.getElementById('backBtn'),add=document.querySelector('.addCenter');
const css=document.createElement('style');css.textContent=`.addCenter{white-space:nowrap!important;overflow:hidden!important}.addCenter::after{content:""!important;display:none!important}.addCenter:hover,.addCenter:focus-visible{width:220px!important;border-radius:999px!important;background:#ce1126!important;color:#fff!important;opacity:1!important;font-size:17px!important;font-weight:750!important}.treeViewport.liveFiltering .addCenter:hover,.treeViewport.liveFiltering .addCenter:focus-visible{background:#ce1126!important}.familyView .kin{pointer-events:auto!important;cursor:pointer!important}.familyView .kin *{pointer-events:none!important}.familyView .kinGraph{cursor:grab!important}.familyView .kinGraph.sirioFamilyDragging{cursor:grabbing!important}`;document.head.appendChild(css);
if(add){const show=()=>{add.classList.add('familyHover');add.textContent='Agregar familia'},hide=()=>{add.classList.remove('familyHover');add.innerHTML='<span class="sirioPlus">+</span>'};add.onmouseenter=show;add.onmouseleave=hide;add.onfocus=show;add.onblur=hide}
let dragging=false,pid=null,sx=0,sy=0,tx=0,ty=0,bx=0,by=0,zoom=1,moved=false;
function apply(animate=false){if(!fg)return;fg.style.transition=animate?'transform .7s cubic-bezier(.16,.85,.2,1)':'none';fg.style.transform=`translate(calc(-50% + ${tx}px),calc(-50% + ${ty}px)) scale(${zoom})`}
function start(e){if(!familyView?.classList.contains('open')||e.button!==0||e.target.closest('.kin,.back'))return;dragging=true;moved=false;pid=e.pointerId;sx=e.clientX;sy=e.clientY;bx=tx;by=ty;fg.classList.add('sirioFamilyDragging');try{fg.setPointerCapture(pid)}catch(_){}e.preventDefault()}
function move(e){if(!dragging||e.pointerId!==pid)return;const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)+Math.abs(dy)>5)moved=true;tx=bx+dx;ty=by+dy;apply(false);e.preventDefault()}
function stop(){if(!dragging)return;dragging=false;fg?.classList.remove('sirioFamilyDragging');try{if(pid!==null&&fg?.hasPointerCapture?.(pid))fg.releasePointerCapture(pid)}catch(_){}pid=null}
fg?.addEventListener('pointerdown',start,true);fg?.addEventListener('pointermove',move,{capture:true,passive:false});['pointerup','pointercancel','lostpointercapture'].forEach(ev=>fg?.addEventListener(ev,stop,true));window.addEventListener('pointerup',stop,true);window.addEventListener('mouseup',stop,true);window.addEventListener('blur',stop,true);window.addEventListener('pointermove',e=>{if(dragging&&e.pointerType==='mouse'&&e.buttons===0)stop()},true);
fg?.addEventListener('dblclick',e=>{if(e.target.closest('.kin'))return;e.preventDefault();zoom=Math.min(1.8,zoom*1.3);apply(true)},true);
if(kinPeople)kinPeople.addEventListener('click',e=>{const node=e.target.closest('.kin');if(!node||moved)return;stop();const nodes=[...kinPeople.querySelectorAll('.kin')],i=nodes.indexOf(node);if(i<0)return;const target=nodes[i+1]||nodes[i-1];if(target&&target!==node){target.click();setTimeout(()=>{zoom=Math.max(.62,zoom*.92);apply(true)},30)}},false);
new MutationObserver(()=>{if(familyView?.classList.contains('open')){tx=0;ty=0;zoom=1;setTimeout(()=>apply(false),40)}}).observe(familyView,{attributes:true,attributeFilter:['class']});
if(back)back.addEventListener('pointerdown',stop,true);
})();