(()=>{
const viewport=document.getElementById('treeViewport'),world=document.getElementById('world'),input=document.getElementById('surname'),familyView=document.getElementById('familyView'),kinPeople=document.getElementById('kinPeople'),back=document.getElementById('backBtn'),add=document.querySelector('.addCenter');
const css=document.createElement('style');css.textContent=`.addCenter{white-space:nowrap!important;overflow:hidden!important}.addCenter::after{content:""!important;display:none!important}.addCenter:hover,.addCenter:focus-visible{width:220px!important;border-radius:999px!important;background:#ce1126!important;color:#fff!important;opacity:1!important;font-size:17px!important;font-weight:750!important}.treeViewport.liveFiltering .addCenter:hover,.treeViewport.liveFiltering .addCenter:focus-visible{background:#ce1126!important}.familyView .kin{pointer-events:auto!important;cursor:pointer!important}.familyView .kin *{pointer-events:none!important}.familyView .kinGraph{cursor:default!important;touch-action:auto!important}.familyView.open:after{content:"Toca una persona para avanzar por la rama"!important}.familyView:not(.open){pointer-events:none!important;visibility:hidden!important}`;document.head.appendChild(css);
if(add){const show=()=>{add.classList.add('familyHover');add.textContent='Agregar familia'},hide=()=>{add.classList.remove('familyHover');add.innerHTML='<span class="sirioPlus">+</span>'};add.onmouseenter=show;add.onmouseleave=hide;add.onfocus=show;add.onblur=hide}
function restoreAddButton(){if(!add)return;add.style.pointerEvents='auto';add.style.zIndex='55';add.classList.remove('familyHover');add.blur();add.innerHTML='<span class="sirioPlus">+</span>'}
function closeFamilyOverlay(){if(!familyView)return;familyView.classList.remove('open');familyView.setAttribute('aria-hidden','true');familyView.style.pointerEvents='none';restoreAddButton();requestAnimationFrame(restoreAddButton);setTimeout(restoreAddButton,80)}
function resetSearchView(){closeFamilyOverlay();viewport?.classList.remove('liveFiltering');document.querySelectorAll('.person').forEach(e=>e.classList.remove('hit','dim','liveHit','liveDim'));document.querySelectorAll('.activePath,.activeDot').forEach(e=>e.classList.remove('activePath','activeDot'));if(world){world.style.transition='transform .8s cubic-bezier(.16,.85,.2,1)';world.style.transform=matchMedia('(max-width:700px)').matches?'translate(-50%,-50%) scale(.36)':'translate(-50%,-50%) scale(.62)'}requestAnimationFrame(()=>viewport?.scrollIntoView({behavior:'smooth',block:'center'}))}
back?.addEventListener('click',()=>{setTimeout(()=>{closeFamilyOverlay();restoreAddButton()},0)},true);
new MutationObserver(()=>{if(familyView?.classList.contains('open')){familyView.style.pointerEvents='auto';familyView.style.visibility='visible';familyView.setAttribute('aria-hidden','false')}else{familyView.style.pointerEvents='none';familyView.style.visibility='hidden';restoreAddButton()}}).observe(familyView,{attributes:true,attributeFilter:['class']});
input?.addEventListener('input',()=>{if(!input.value.trim())setTimeout(resetSearchView,0)},true);input?.addEventListener('search',()=>{if(!input.value.trim())setTimeout(resetSearchView,0)},true);
})();