(()=>{
const viewport=document.getElementById('treeViewport'),familyView=document.getElementById('familyView'),fg=familyView?.querySelector('.kinGraph'),kinPeople=document.getElementById('kinPeople'),back=document.getElementById('backBtn'),add=document.querySelector('.addCenter');
const css=document.createElement('style');css.textContent=`.addCenter{white-space:nowrap!important;overflow:hidden!important}.addCenter::after{content:""!important;display:none!important}.addCenter:hover,.addCenter:focus-visible{width:220px!important;border-radius:999px!important;background:#ce1126!important;color:#fff!important;opacity:1!important;font-size:17px!important;font-weight:750!important}.treeViewport.liveFiltering .addCenter:hover,.treeViewport.liveFiltering .addCenter:focus-visible{background:#ce1126!important}.familyView .kin{pointer-events:auto!important;cursor:pointer!important}.familyView .kin *{pointer-events:none!important}`;document.head.appendChild(css);
if(add){add.addEventListener('mouseenter',()=>{add.classList.add('familyHover');add.textContent='Agregar familia'});add.addEventListener('mouseleave',()=>{add.classList.remove('familyHover');add.innerHTML='<span class="sirioPlus">+</span>'})}
function release(){document.body.style.cursor='';try{if(viewport?.hasPointerCapture?.(window.__sirioPointer))viewport.releasePointerCapture(window.__sirioPointer)}catch(_){}window.__sirioPointer=null}
window.addEventListener('pointerup',release,true);window.addEventListener('mouseup',release,true);window.addEventListener('blur',release,true);
if(back)back.addEventListener('pointerdown',release,true);
let zoom=1;function applyZoom(){if(!fg)return;fg.style.transition='transform .65s cubic-bezier(.16,.85,.2,1)';fg.style.transform=`translate(-50%,-50%) scale(${zoom})`}
if(fg)fg.addEventListener('dblclick',e=>{if(e.target.closest('.kin'))return;e.preventDefault();zoom=Math.min(1.65,zoom*1.3);applyZoom()},true);
})();